# Generated by Django 5.0.4 on 2024-05-05 17:02

import django.db.models.deletion
import recordmap.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Executor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('address', models.TextField(blank=True, max_length=250, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('executor_contact', models.CharField(max_length=65, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('number', models.IntegerField(unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('NEW', 'Новое обращение'), ('PUBLISHED', 'Опубликовано'), ('SENT', 'Обращение отправлено'), ('INWORK', 'Дан ответ'), ('DONE', 'Выполнено'), ('FAIL', 'Не выполнено')], default='Новое обращение', max_length=25)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=14, max_digits=17, null=True)),
                ('longitude', models.DecimalField(decimal_places=14, max_digits=17, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IncidentExecutorRelateDocs',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('response_doc', models.FileField(blank=True, null=True, upload_to='docs/responses')),
                ('request_doc', models.FileField(blank=True, null=True, upload_to='docs/requests')),
                ('date_send_request', models.DateTimeField(blank=True, null=True)),
                ('date_get_response', models.DateTimeField(blank=True, null=True)),
                ('executor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='executor_related', to='recordmap.executor')),
                ('incident', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='executor_related', to='recordmap.incident')),
            ],
        ),
        migrations.CreateModel(
            name='IncidentPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('path', models.ImageField(upload_to=recordmap.models.incident_images_path)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='recordmap.incident')),
            ],
        ),
    ]
