# Generated by Django 5.0.4 on 2024-05-08 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordmap', '0003_alter_executor_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='text',
            field=models.TextField(max_length=350),
        ),
    ]
