# Generated by Django 5.0.4 on 2024-05-08 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordmap', '0004_alter_incident_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('Новое обращение', 'Новое обращение'), ('Опубликовано', 'Опубликовано'), ('Обращение отправлено', 'Обращение отправлено'), ('Дан ответ', 'Дан ответ'), ('Выполнено', 'Выполнено'), ('Не выполнено', 'Не выполнено')], default='Новое обращение', max_length=25),
        ),
    ]
