# Generated by Django 5.0.4 on 2024-05-08 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordmap', '0005_alter_incident_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('NEW', 'Новое обращение'), ('PUBLISHED', 'Опубликовано'), ('SENT', 'Обращение отправлено'), ('INWORK', 'Дан ответ'), ('DONE', 'Выполнено'), ('FAIL', 'Не выполнено')], default='NEW', max_length=25),
        ),
    ]
