# Generated by Django 5.0.4 on 2024-05-12 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordmap', '0007_alter_incident_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='number',
            field=models.IntegerField(editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='incidentexecutorrelatedocs',
            name='incident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executor_related', to='recordmap.incident'),
        ),
    ]
