# Generated by Django 5.0.4 on 2024-05-13 03:24

import recordmap.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordmap', '0009_alter_incidentexecutorrelatedocs_date_get_response_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentexecutorrelatedocs',
            name='request_doc',
            field=models.FileField(blank=True, null=True, upload_to=recordmap.models.request_doc_path),
        ),
        migrations.AlterField(
            model_name='incidentexecutorrelatedocs',
            name='response_doc',
            field=models.FileField(blank=True, null=True, upload_to=recordmap.models.response_doc_path),
        ),
    ]
